### ISSUE TITLE
URL-specific saving approach is too limiting

### ISSUE THREAD

**Issue by revad** [ettoolong/TextareaCache#11]
(This applies to TextareaCache **Lite**. I'm not clear if this is the correct place.)

I see that it stores text is keyed in on the whole URL. This means that you cannot recover it if the URL is not identical - which includes query strings.

For example, I see that I have stored text for this URL:
http://mudcat.org/thread.cfm?threadid=161911&messages=18

But that '18' is just the number of messages that existed at the time I started to post. If the post fails, by the time I re-try it somebody might have added a message and 18 becomes 19. So I cannot recover the text (I tried it).

I think this is a simple example of a wider problem. The full URL often changes if you return to an input form - especially but not only query strings (session IDs for example). Without understanding the whole URL structure you don't know what to key it on. You could exclude query strings, fragment IDs, etc. and just use the domain or origin but it would still limit the user's ability to recover the text. For example I can use mudcat.org or www.mudcat.org - both are the same site - it depends what's in a link or bookmark. 

The old TAC approach of allowing the user to select the appropriate text - whatever page it came from - is better. Often you start posting into one form or forum and decide it would be better posted elsewhere; TAC could do that.

BTW How are you going to limit the size of <profile>/browser-extension-data/textarea-cache-lite@wildsky.cc/storage.js ?

**Comment by wildskyf** [comment]
Hi, revad

> (This applies to TextareaCache Lite. I'm not clear if this is the correct place.)

Yeah This is the place to report bug, issue, enhancement about TCL.
Feel free to open any other issue about TCL or TC in this repo.

> I see that it stores text is keyed in on the whole URL. This means that you cannot recover it if the URL is not identical - which includes query strings.

Got you. I will change the appear rule of TCL button, and think about how to change the label rule to save data in order to ensure users could access their data anywhere.

> BTW How are you going to limit the size of /browser-extension-data/textarea-cache-lite@wildsky.cc/storage.js ?

This could be a new issue, but I think Web Extension API is not ready to provide the way to finish this feature. So... maybe we need to wait until it is possible.

**Comment by revad** [comment]
I think the two questions are related. Keying storage.local on the entire URL means there are many more keys. Using my mudcat.org example, if I post to the same thread 10 times there will be 10 keys. And the text can be very long. But if you key on mudcat.org then you could have a single record containing a pushdown stack of, say, max 10 entries. An individual user is not going to use thousands of sites.

You could show the user the whole URL in the pop-up, but probably it's unnecessary. I usually want to retrieve the latest, or an earlier version of, a text that I recognise.

Whether to key on the whole origin - www.mudcat.org - or the domain - mudcat.org - needs thought. mudcat is only an example; what about google - mail.google.com or just google.com - or google.* ? Or facebook? 

Dave

**Comment by wildskyf** [comment]
Hi @raved,

I have change the entry to a alway-showed button, so that you could access all data you saved. And also, I change the rule to identify data: `Date + Page Title + serial no in that page`. It is like the Textarea Cache so I think this rule is okay.

Feel free to provide any opinions & suggestions about this issue. And if the 2.0.1 update solved your problem, please close this issue. :) If you have any other problems or suggestions for topic not about this issue, feel free to open a new issue!

**Comment by revad** [comment]
That works better.

The list of saved texts can get quite long. Normally you'd want the last one saved. Is it possible to put them in reverse order, so the latest shows when you click the icon, oldest one at the bottom?

Even better would be to select the site (eg. mudcat.org), then have a secondary list of texts for that site appear for you select one. Each list latest item first. Future enhancement?

The page title is truncated in the selector popup - i.e. it's shorter than the title you store. Can you think of a way of allowing the user to see all of it, in case the important part is at the right-hand end? Scroll it sideways on mouse-over? Another enhancement?

But overall, quite usable. Thanks

**Comment by wildskyf** [comment]
Hi @revad ,

I have reverse the order, make the latest shows when you click the icon, oldest one at the bottom.

And I just add another feature, which let you see the whole title in the selector, you could get more information in #26.

Feel free to open another issue. :)
